version: '2'
services:
  ckan:
    image: geosolutionsit/dati-ckan-docker:ckan-agid-devel
    environment:
      CKAN_SITE_URL: http://localhost:5000
      CKAN_INI_PATH: /etc/ckan/default/ckan.ini
      CKAN_SQLALCHEMY_URL: db.bdoe-data.svc://ckan:ckan@db:5432/
      CKAN_REDIS_URL: redis://redis:6379/
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_DB_USER: ckan
      CKAN_DB_PASSWORD: ckan
    stdin_open: true
    entrypoint:
    - /wait-for-services.sh
    - /ckan-entrypoint.sh
    tty: true
    links:
    - db:db
    - redis:redis
    - solr:solr
    ports:
    - "5000:5000"
    command:
    - paster
    - serve
    - /etc/ckan/default/ckan.ini
    labels:
      name: ckan-agid-devel
      io.rancher.container.pull_image: always


