ckan:
  container_name: ckan
  image: geosolutionsit/ckan-agid:devel
  links:
      - db
      - solr
      - redis
  ports:
      - "5000:5000"
  environment:
      - CKAN_SITE_URL=http://localhost:5000
      - DB_PORT_5432_TCP_ADDR=db
      - SOLR_PORT_8983_TCP_ADDR=solr
      - REDIS_PORT_6379_TCP_ADDR=redis
  entrypoint: ["/wait-for-services.sh", "/ckan-entrypoint.sh"]
  command: ["paster","serve","/etc/ckan/default/ckan.ini"]

db:
  container_name: db
  image: ckan/postgresql:latest
  
solr:
  container_name: solr
  image: geosolutionsit/ckan-solr:devel
    
redis:
  container_name: redis
  image: redis:latest

